apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: aiops
build:
  artifacts:
  - image: huseyinkervan/aiops
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s-*
